-- Phase 1 schema: identity, profiles, youth safety, media, social, AI evidence, player intelligence.
-- Conventions: UUIDv7 keys generated by the application, timestamptz everywhere,
-- no video binaries in the database (object keys only), soft state via explicit status columns.

CREATE EXTENSION IF NOT EXISTS citext;

-- ---------------------------------------------------------------- geography
-- Broad regions only. People are never stored with coordinates.
CREATE TABLE regions (
  id           uuid PRIMARY KEY,
  kind         text NOT NULL CHECK (kind IN ('macro', 'country', 'admin_area', 'city')),
  code         text NOT NULL UNIQUE,            -- 'north-africa', 'EG', 'EG-C', 'EG-C-cairo'
  parent_id    uuid REFERENCES regions(id),
  country_code char(2),                         -- ISO 3166-1 alpha-2 for country and below
  names        jsonb NOT NULL                   -- {"en": "Cairo", "ar": "القاهرة"}
);
CREATE INDEX regions_parent_idx ON regions (parent_id);

-- ---------------------------------------------------------------- identity
CREATE TABLE users (
  id              uuid PRIMARY KEY,
  idp_subject     text NOT NULL UNIQUE,         -- subject from the identity provider
  email           citext UNIQUE,
  email_verified  boolean NOT NULL DEFAULT false,
  locale          text NOT NULL DEFAULT 'en',
  status          text NOT NULL DEFAULT 'pending_consent'
                  CHECK (status IN ('pending_consent', 'active', 'suspended', 'deleted')),
  created_at      timestamptz NOT NULL DEFAULT now(),
  deleted_at      timestamptz
);

CREATE TABLE user_roles (
  user_id    uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  role       text NOT NULL CHECK (role IN ('player', 'fan', 'creator', 'coach', 'scout',
                                           'academy', 'club', 'moderator', 'admin')),
  granted_at timestamptz NOT NULL DEFAULT now(),
  granted_by uuid REFERENCES users(id),
  PRIMARY KEY (user_id, role)
);

-- Date of birth is sensitive; the application encrypts it before storage.
CREATE TABLE age_records (
  user_id            uuid PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
  dob_encrypted      bytea NOT NULL,
  country_code       char(2) NOT NULL,
  age_band           text NOT NULL CHECK (age_band IN ('u13', 'u16', 'u18', 'adult')),
  guardian_required  boolean NOT NULL,
  recorded_at        timestamptz NOT NULL DEFAULT now()
);

-- ---------------------------------------------------------------- youth safety
CREATE TABLE guardian_invitations (
  id              uuid PRIMARY KEY,
  minor_user_id   uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  guardian_email  citext NOT NULL,
  token_hash      bytea NOT NULL UNIQUE,         -- only the hash of the emailed token is stored
  status          text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'accepted', 'declined', 'expired')),
  expires_at      timestamptz NOT NULL,
  created_at      timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE guardian_relationships (
  guardian_user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  minor_user_id    uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  status           text NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'revoked')),
  created_at       timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (guardian_user_id, minor_user_id)
);

-- Every consent decision is an immutable row; the current state is the latest row per (subject, purpose).
CREATE TABLE consents (
  id              uuid PRIMARY KEY,
  subject_user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  granted_by      uuid NOT NULL REFERENCES users(id),     -- the subject, or their guardian
  purpose         text NOT NULL CHECK (purpose IN ('account', 'public_profile', 'ai_analysis',
                                                   'model_training', 'leaderboards', 'scout_contact')),
  granted         boolean NOT NULL,
  policy_version  text NOT NULL,
  created_at      timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX consents_current_idx ON consents (subject_user_id, purpose, created_at DESC);

CREATE TABLE privacy_settings (
  user_id               uuid PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
  profile_visibility    text NOT NULL DEFAULT 'public' CHECK (profile_visibility IN ('public', 'followers', 'private')),
  region_precision      text NOT NULL DEFAULT 'country' CHECK (region_precision IN ('macro', 'country', 'city')),
  comments              text NOT NULL DEFAULT 'everyone' CHECK (comments IN ('everyone', 'followers', 'off')),
  direct_messages       boolean NOT NULL DEFAULT false,
  updated_at            timestamptz NOT NULL DEFAULT now()
);

-- ---------------------------------------------------------------- profiles
CREATE TABLE profiles (
  user_id       uuid PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
  handle        citext NOT NULL UNIQUE,
  display_name  text NOT NULL,
  bio           text,
  avatar_key    text,
  region_id     uuid REFERENCES regions(id),
  created_at    timestamptz NOT NULL DEFAULT now(),
  updated_at    timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE player_profiles (
  user_id               uuid PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
  primary_position      text CHECK (primary_position IN ('GK','CB','LB','RB','DM','CM','AM','LW','RW','ST')),
  secondary_positions   text[] NOT NULL DEFAULT '{}',
  preferred_foot        text CHECK (preferred_foot IN ('left', 'right', 'both')),
  height_cm             smallint,
  -- these facts are user-provided and labeled as such wherever shown
  created_at            timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX player_profiles_position_idx ON player_profiles (primary_position);

-- ---------------------------------------------------------------- media
CREATE TABLE videos (
  id               uuid PRIMARY KEY,
  owner_user_id    uuid NOT NULL REFERENCES users(id),
  status           text NOT NULL DEFAULT 'awaiting_upload'
                   CHECK (status IN ('awaiting_upload', 'uploaded', 'processing', 'ready', 'rejected', 'deleted')),
  original_key     text NOT NULL UNIQUE,
  content_type     text NOT NULL CHECK (content_type IN ('video/mp4', 'video/quicktime', 'video/webm')),
  size_bytes       bigint NOT NULL CHECK (size_bytes > 0),
  video_type       text NOT NULL CHECK (video_type IN ('match','training','skill_challenge','freestyle','goalkeeper',
                                                       'skills_compilation','tactical_sequence','shooting','passing',
                                                       'dribbling','defending')),
  subject          text NOT NULL CHECK (subject IN ('me', 'another_player', 'multiple_players', 'unknown')),
  caption          text,
  region_id        uuid REFERENCES regions(id),
  duration_ms      integer,
  width            integer,
  height           integer,
  fps              numeric(6,3),
  hls_key          text,
  thumbnail_key    text,
  visibility       text NOT NULL DEFAULT 'public' CHECK (visibility IN ('public', 'followers', 'private')),
  created_at       timestamptz NOT NULL DEFAULT now(),
  ready_at         timestamptz,
  deleted_at       timestamptz
);
CREATE INDEX videos_feed_idx ON videos (created_at DESC) WHERE status = 'ready' AND visibility = 'public';
CREATE INDEX videos_owner_idx ON videos (owner_user_id, created_at DESC);
CREATE INDEX videos_region_idx ON videos (region_id, created_at DESC) WHERE status = 'ready';

CREATE TABLE video_hashes (
  video_id   uuid PRIMARY KEY REFERENCES videos(id) ON DELETE CASCADE,
  sha256     bytea NOT NULL,
  phash      bigint[]
);
CREATE INDEX video_hashes_sha_idx ON video_hashes (sha256);

-- ---------------------------------------------------------------- social
CREATE TABLE follows (
  follower_id  uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  followee_id  uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  created_at   timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (follower_id, followee_id),
  CHECK (follower_id <> followee_id)
);
CREATE INDEX follows_followee_idx ON follows (followee_id, created_at DESC);

CREATE TABLE likes (
  user_id    uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  video_id   uuid NOT NULL REFERENCES videos(id) ON DELETE CASCADE,
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (video_id, user_id)
);

CREATE TABLE comments (
  id               uuid PRIMARY KEY,
  video_id         uuid NOT NULL REFERENCES videos(id) ON DELETE CASCADE,
  author_id        uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  parent_id        uuid REFERENCES comments(id) ON DELETE CASCADE,
  body             text NOT NULL CHECK (char_length(body) BETWEEN 1 AND 2000),
  moderation       text NOT NULL DEFAULT 'pending' CHECK (moderation IN ('pending', 'visible', 'held', 'removed')),
  created_at       timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX comments_video_idx ON comments (video_id, created_at DESC);

CREATE TABLE blocks (
  blocker_id  uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  blocked_id  uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  created_at  timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (blocker_id, blocked_id)
);

CREATE TABLE reports (
  id            uuid PRIMARY KEY,
  reporter_id   uuid NOT NULL REFERENCES users(id),
  target_kind   text NOT NULL CHECK (target_kind IN ('video', 'comment', 'user')),
  target_id     uuid NOT NULL,
  reason        text NOT NULL CHECK (reason IN ('spam','harassment','hate','sexual','violence','child_safety',
                                                'impersonation','copyright','stolen_video','other')),
  details       text,
  status        text NOT NULL DEFAULT 'open' CHECK (status IN ('open', 'actioned', 'dismissed')),
  priority      smallint NOT NULL DEFAULT 2,     -- child safety and minors are raised to 0
  created_at    timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX reports_queue_idx ON reports (status, priority, created_at);

-- ---------------------------------------------------------------- AI evidence
CREATE TABLE target_selections (
  id                 uuid PRIMARY KEY,
  video_id           uuid NOT NULL REFERENCES videos(id) ON DELETE CASCADE,
  selected_by        uuid NOT NULL REFERENCES users(id),
  frame_ms           integer NOT NULL CHECK (frame_ms >= 0),
  box                jsonb NOT NULL,              -- {"x":0.41,"y":0.22,"w":0.08,"h":0.31}, normalized 0..1
  claimed_player_id  uuid REFERENCES users(id),   -- whom the uploader says this is
  confirmed          boolean NOT NULL DEFAULT false, -- set only by the claimed player (or their guardian)
  created_at         timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE analysis_runs (
  id                   uuid PRIMARY KEY,
  video_id             uuid NOT NULL REFERENCES videos(id) ON DELETE CASCADE,
  target_selection_id  uuid NOT NULL REFERENCES target_selections(id),
  requested_by         uuid NOT NULL REFERENCES users(id),
  pipeline_version     text NOT NULL,
  tier                 text NOT NULL CHECK (tier IN ('basic', 'advanced', 'batch')),
  status               text NOT NULL DEFAULT 'queued'
                       CHECK (status IN ('queued','running','done','failed','rejected_quality')),
  quality_score        numeric(5,2),
  readiness            numeric(4,3),
  limitations          jsonb NOT NULL DEFAULT '[]',
  cost_usd_micros      bigint,
  created_at           timestamptz NOT NULL DEFAULT now(),
  finished_at          timestamptz
);
CREATE INDEX analysis_runs_video_idx ON analysis_runs (video_id, created_at DESC);

CREATE TABLE agent_runs (
  id               uuid PRIMARY KEY,
  analysis_run_id  uuid NOT NULL REFERENCES analysis_runs(id) ON DELETE CASCADE,
  agent            text NOT NULL,
  version          text NOT NULL,
  status           text NOT NULL CHECK (status IN ('ok', 'failed', 'skipped')),
  confidence       numeric(4,3),
  limitations      jsonb NOT NULL DEFAULT '[]',
  errors           jsonb NOT NULL DEFAULT '[]',
  latency_ms       integer,
  cost_usd_micros  bigint,
  cache_key        text,
  created_at       timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX agent_runs_cache_idx ON agent_runs (cache_key) WHERE cache_key IS NOT NULL;

CREATE TABLE observations (
  id               uuid PRIMARY KEY,
  analysis_run_id  uuid NOT NULL REFERENCES analysis_runs(id) ON DELETE CASCADE,
  agent_run_id     uuid NOT NULL REFERENCES agent_runs(id) ON DELETE CASCADE,
  skill            text NOT NULL,
  event_type       text NOT NULL,
  outcome          text NOT NULL CHECK (outcome IN ('success', 'fail', 'unknown')),
  t_start_ms       integer NOT NULL,
  t_end_ms         integer NOT NULL CHECK (t_end_ms >= t_start_ms),
  confidence       numeric(4,3) NOT NULL CHECK (confidence BETWEEN 0 AND 1),
  context          jsonb NOT NULL DEFAULT '{}',
  excluded_reason  text
);
CREATE INDEX observations_run_idx ON observations (analysis_run_id, skill);

-- ---------------------------------------------------------------- player intelligence
CREATE TABLE skill_scores (
  id                 uuid PRIMARY KEY,
  player_user_id     uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  skill              text NOT NULL,
  score              numeric(5,2),               -- NULL = insufficient evidence
  status             text NOT NULL CHECK (status IN ('assessed', 'insufficient_evidence')),
  confidence         numeric(4,3) NOT NULL,
  evidence_count     integer NOT NULL,
  evidence_quality   text NOT NULL CHECK (evidence_quality IN ('low', 'medium', 'high')),
  method_version     text NOT NULL,
  explanation        jsonb NOT NULL,            -- positive/negative indicators, limitations
  computed_at        timestamptz NOT NULL DEFAULT now(),
  superseded_by      uuid REFERENCES skill_scores(id)
);
CREATE INDEX skill_scores_current_idx ON skill_scores (player_user_id, skill) WHERE superseded_by IS NULL;

CREATE TABLE skill_score_evidence (
  skill_score_id  uuid NOT NULL REFERENCES skill_scores(id) ON DELETE CASCADE,
  observation_id  uuid NOT NULL REFERENCES observations(id) ON DELETE CASCADE,
  weight          numeric NOT NULL,
  PRIMARY KEY (skill_score_id, observation_id)
);

CREATE TABLE player_dna_versions (
  id               uuid PRIMARY KEY,
  player_user_id   uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  version          integer NOT NULL,
  method_version   text NOT NULL,
  dna              jsonb NOT NULL,
  created_at       timestamptz NOT NULL DEFAULT now(),
  UNIQUE (player_user_id, version)
);

-- Kept apart from football ability on purpose. Never joined into a single ranking.
CREATE TABLE popularity_scores (
  user_id     uuid PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
  score       numeric(5,2) NOT NULL,
  computed_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE trust_scores (
  user_id     uuid PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
  score       numeric(5,2) NOT NULL,
  computed_at timestamptz NOT NULL DEFAULT now()
);

-- ---------------------------------------------------------------- platform
CREATE TABLE outbox (
  id            bigserial PRIMARY KEY,
  topic         text NOT NULL,
  payload       jsonb NOT NULL,
  created_at    timestamptz NOT NULL DEFAULT now(),
  published_at  timestamptz
);
CREATE INDEX outbox_unpublished_idx ON outbox (id) WHERE published_at IS NULL;

CREATE TABLE idempotency_keys (
  user_id       uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  key           text NOT NULL,
  request_hash  text NOT NULL,
  response      jsonb NOT NULL,
  created_at    timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (user_id, key)
);

-- Append-only, enforced by the trigger below.
CREATE TABLE audit_logs (
  id           bigserial PRIMARY KEY,
  actor_id     uuid,
  action       text NOT NULL,
  target_kind  text,
  target_id    uuid,
  metadata     jsonb NOT NULL DEFAULT '{}',
  created_at   timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX audit_logs_target_idx ON audit_logs (target_kind, target_id, created_at DESC);

CREATE FUNCTION audit_logs_append_only() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  RAISE EXCEPTION 'audit_logs is append-only';
END $$;
CREATE TRIGGER audit_logs_no_update BEFORE UPDATE OR DELETE ON audit_logs
  FOR EACH ROW EXECUTE FUNCTION audit_logs_append_only();
