-- KICKSCOUT schema: identity, profiles, youth safety, videos, AI tags, moderation, social,
-- challenges, scout workflows, notifications and the background job queue.
-- Conventions: UUIDv7 keys generated by the application, timestamptz everywhere,
-- no video binaries in the database (object keys only), soft state via explicit status columns.

CREATE EXTENSION IF NOT EXISTS citext;


-- ---------------------------------------------------------------- geography
-- Broad regions only. People are never stored with coordinates.
CREATE TABLE regions (
  id           uuid PRIMARY KEY,
  kind         text NOT NULL CHECK (kind IN ('macro', 'country', 'admin_area', 'city')),
  code         text NOT NULL UNIQUE,            -- 'north-africa', 'EG', 'EG-C', 'EG-C-cairo'
  parent_id    uuid REFERENCES regions(id),
  country_code char(2),                         -- ISO 3166-1 alpha-2 for country and below
  names        jsonb NOT NULL                   -- {"en": "Cairo", "ar": "القاهرة"}
);
CREATE INDEX regions_parent_idx ON regions (parent_id);

-- ---------------------------------------------------------------- identity
CREATE TABLE users (
  id              uuid PRIMARY KEY,
  idp_subject     text NOT NULL UNIQUE,         -- subject from the identity provider
  email           citext UNIQUE,
  email_verified  boolean NOT NULL DEFAULT false,
  locale          text NOT NULL DEFAULT 'en',
  is_demo         boolean NOT NULL DEFAULT false,   -- seeded demo accounts, always labeled in the UI
  status          text NOT NULL DEFAULT 'pending_consent'
                  CHECK (status IN ('pending_consent', 'active', 'suspended', 'deleted')),
  created_at      timestamptz NOT NULL DEFAULT now(),
  deleted_at      timestamptz
);

CREATE TABLE user_roles (
  user_id    uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  -- 'scout' is granted only when a scout verification request is approved.
  role       text NOT NULL CHECK (role IN ('player', 'fan', 'scout', 'moderator', 'admin')),
  granted_at timestamptz NOT NULL DEFAULT now(),
  granted_by uuid REFERENCES users(id),
  PRIMARY KEY (user_id, role)
);

-- Date of birth is sensitive; the application encrypts it before storage.
CREATE TABLE age_records (
  user_id            uuid PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
  dob_encrypted      bytea NOT NULL,
  country_code       char(2) NOT NULL,
  age_band           text NOT NULL CHECK (age_band IN ('u13', 'u16', 'u18', 'adult')),
  guardian_required  boolean NOT NULL,
  recorded_at        timestamptz NOT NULL DEFAULT now()
);

-- Per-country age rules, editable by admins. A row counts only once legal review is recorded;
-- otherwise the conservative default (guardian consent under 18) applies.
CREATE TABLE jurisdiction_rules (
  country_code          char(2) PRIMARY KEY,
  minimum_age           smallint NOT NULL DEFAULT 13 CHECK (minimum_age >= 13),
  guardian_consent_age  smallint NOT NULL CHECK (guardian_consent_age BETWEEN 13 AND 21),
  legally_reviewed      boolean NOT NULL DEFAULT false,
  source                text,
  updated_by            uuid,
  updated_at            timestamptz NOT NULL DEFAULT now()
);

-- ---------------------------------------------------------------- youth safety
CREATE TABLE guardian_invitations (
  id              uuid PRIMARY KEY,
  minor_user_id   uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  guardian_email  citext NOT NULL,
  token_hash      bytea NOT NULL UNIQUE,         -- only the hash of the emailed token is stored
  status          text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'accepted', 'declined', 'expired')),
  expires_at      timestamptz NOT NULL,
  created_at      timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE guardian_relationships (
  guardian_user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  minor_user_id    uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  status           text NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'revoked')),
  created_at       timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (guardian_user_id, minor_user_id)
);

-- Every consent decision is an immutable row; the current state is the latest row per (subject, purpose).
CREATE TABLE consents (
  id              uuid PRIMARY KEY,
  subject_user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  granted_by      uuid NOT NULL REFERENCES users(id),     -- the subject, or their guardian
  purpose         text NOT NULL CHECK (purpose IN ('account', 'public_profile', 'scout_contact', 'model_training')),
  granted         boolean NOT NULL,
  policy_version  text NOT NULL,
  created_at      timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX consents_current_idx ON consents (subject_user_id, purpose, created_at DESC);

CREATE TABLE privacy_settings (
  user_id               uuid PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
  profile_visibility    text NOT NULL DEFAULT 'public' CHECK (profile_visibility IN ('public', 'followers', 'private')),
  region_precision      text NOT NULL DEFAULT 'country' CHECK (region_precision IN ('macro', 'country', 'city')),
  comments              text NOT NULL DEFAULT 'everyone' CHECK (comments IN ('everyone', 'followers', 'off')),
  direct_messages       boolean NOT NULL DEFAULT false,
  updated_at            timestamptz NOT NULL DEFAULT now()
);

-- ---------------------------------------------------------------- profiles
CREATE TABLE profiles (
  user_id       uuid PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
  handle        citext NOT NULL UNIQUE,
  display_name  text NOT NULL,
  bio           text,
  avatar_key    text,
  region_id     uuid REFERENCES regions(id),
  verified_at   timestamptz,                    -- set only by an approved verification request
  created_at    timestamptz NOT NULL DEFAULT now(),
  updated_at    timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE player_profiles (
  user_id               uuid PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
  primary_position      text CHECK (primary_position IN ('GK','CB','LB','RB','DM','CM','AM','LW','RW','ST')),
  secondary_positions   text[] NOT NULL DEFAULT '{}',
  preferred_foot        text CHECK (preferred_foot IN ('left', 'right', 'both')),
  height_cm             smallint,
  -- these facts are user-provided and labeled as such wherever shown
  created_at            timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX player_profiles_position_idx ON player_profiles (primary_position);

-- ---------------------------------------------------------------- taxonomy
CREATE TABLE skills (
  key        text PRIMARY KEY,                  -- 'elastico', 'step_over'
  category   text NOT NULL CHECK (category IN ('dribbling', 'control', 'passing', 'shooting', 'athletic', 'defending', 'goalkeeping', 'freestyle')),
  names      jsonb NOT NULL,                    -- {"en": "Elastico", "ar": "إلاستيكو"}
  sort_order smallint NOT NULL DEFAULT 0
);

-- ---------------------------------------------------------------- videos
CREATE TABLE videos (
  id               uuid PRIMARY KEY,
  owner_user_id    uuid NOT NULL REFERENCES users(id),
  status           text NOT NULL DEFAULT 'uploading'
                   CHECK (status IN ('uploading', 'processing', 'analyzing', 'review_required', 'published', 'rejected', 'failed', 'deleted')),
  status_reason    text,
  original_key     text NOT NULL UNIQUE,
  declared_type    text NOT NULL,                -- what the client said; never trusted
  size_bytes       bigint NOT NULL CHECK (size_bytes > 0),
  title            text NOT NULL CHECK (char_length(title) BETWEEN 1 AND 100),
  description      text CHECK (char_length(description) <= 500),
  skill_key        text REFERENCES skills(key),  -- chosen by the uploader
  position         text CHECK (position IN ('GK','CB','LB','RB','DM','CM','AM','LW','RW','ST')),
  foot             text CHECK (foot IN ('left', 'right', 'both')),
  context          text CHECK (context IN ('match', 'training', 'freestyle', 'challenge', 'other')),
  visibility       text NOT NULL DEFAULT 'public' CHECK (visibility IN ('public', 'followers', 'private')),
  region_id        uuid REFERENCES regions(id),
  trim_start_ms    integer CHECK (trim_start_ms >= 0),
  trim_end_ms      integer CHECK (trim_end_ms > trim_start_ms),
  -- written by the worker after probing the real file
  detected_format  text,
  duration_ms      integer,
  width            integer,
  height           integer,
  playback_key     text,
  thumbnail_key    text,
  sha256           bytea,
  -- AI moderation verdict; humans decide anything that is not clearly safe
  moderation       text CHECK (moderation IN ('safe', 'flagged', 'review_required', 'rejected')),
  football_present boolean,
  players_visible  smallint,
  ai_summary       jsonb,                        -- raw structured AI output, kept for audit
  created_at       timestamptz NOT NULL DEFAULT now(),
  published_at     timestamptz,
  deleted_at       timestamptz
);
CREATE INDEX videos_feed_idx ON videos (published_at DESC, id DESC) WHERE status = 'published' AND visibility = 'public';
CREATE INDEX videos_owner_idx ON videos (owner_user_id, created_at DESC);
CREATE INDEX videos_skill_idx ON videos (skill_key, published_at DESC) WHERE status = 'published';
CREATE INDEX videos_sha_idx ON videos (sha256) WHERE sha256 IS NOT NULL;
CREATE INDEX videos_text_idx ON videos USING gin (to_tsvector('simple', title || ' ' || coalesce(description, '')));

-- Skill tags. AI suggestions and the player's own corrections are separate rows, so it is always
-- clear which tags came from the model. A rejected AI tag stays for audit but is never shown.
CREATE TABLE video_skills (
  video_id    uuid NOT NULL REFERENCES videos(id) ON DELETE CASCADE,
  skill_key   text NOT NULL REFERENCES skills(key),
  source      text NOT NULL CHECK (source IN ('ai', 'user')),
  confidence  numeric(4,3) CHECK (confidence BETWEEN 0 AND 1),   -- AI only
  status      text NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'rejected')),
  created_at  timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (video_id, skill_key, source)
);
CREATE INDEX video_skills_skill_idx ON video_skills (skill_key) WHERE status = 'active';

CREATE TABLE video_hashtags (
  video_id  uuid NOT NULL REFERENCES videos(id) ON DELETE CASCADE,
  tag       citext NOT NULL CHECK (tag ~ '^[[:alnum:]_]{1,40}$'),
  PRIMARY KEY (video_id, tag)
);
CREATE INDEX video_hashtags_tag_idx ON video_hashtags (tag);

-- One row per viewer per video per day; feeds trending and Talent Radar without storing watch histories forever.
CREATE TABLE video_views (
  video_id    uuid NOT NULL REFERENCES videos(id) ON DELETE CASCADE,
  viewer_key  text NOT NULL,                     -- user id, or a salted hash for signed-out viewers
  day         date NOT NULL,
  PRIMARY KEY (video_id, viewer_key, day)
);
CREATE INDEX video_views_day_idx ON video_views (day, video_id);

-- ---------------------------------------------------------------- social
CREATE TABLE follows (
  follower_id  uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  followee_id  uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  created_at   timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (follower_id, followee_id),
  CHECK (follower_id <> followee_id)
);
CREATE INDEX follows_followee_idx ON follows (followee_id, created_at DESC);

CREATE TABLE likes (
  user_id    uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  video_id   uuid NOT NULL REFERENCES videos(id) ON DELETE CASCADE,
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (video_id, user_id)
);
CREATE INDEX likes_recent_idx ON likes (created_at, video_id);

CREATE TABLE saves (
  user_id    uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  video_id   uuid NOT NULL REFERENCES videos(id) ON DELETE CASCADE,
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (user_id, video_id)
);
CREATE INDEX saves_video_idx ON saves (video_id);

CREATE TABLE comments (
  id               uuid PRIMARY KEY,
  video_id         uuid NOT NULL REFERENCES videos(id) ON DELETE CASCADE,
  author_id        uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  parent_id        uuid REFERENCES comments(id) ON DELETE CASCADE,
  body             text NOT NULL CHECK (char_length(body) BETWEEN 1 AND 2000),
  moderation       text NOT NULL DEFAULT 'pending' CHECK (moderation IN ('pending', 'visible', 'held', 'removed')),
  created_at       timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX comments_video_idx ON comments (video_id, created_at DESC);

CREATE TABLE blocks (
  blocker_id  uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  blocked_id  uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  created_at  timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (blocker_id, blocked_id)
);

CREATE TABLE reports (
  id            uuid PRIMARY KEY,
  reporter_id   uuid NOT NULL REFERENCES users(id),
  target_kind   text NOT NULL CHECK (target_kind IN ('video', 'comment', 'user')),
  target_id     uuid NOT NULL,
  reason        text NOT NULL CHECK (reason IN ('spam','harassment','hate','sexual','violence','dangerous','child_safety',
                                                'impersonation','copyright','stolen_video','scam','not_football','other')),
  details       text,
  status        text NOT NULL DEFAULT 'open' CHECK (status IN ('open', 'actioned', 'dismissed')),
  priority      smallint NOT NULL DEFAULT 2,     -- child safety and minors are raised to 0
  created_at    timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX reports_queue_idx ON reports (status, priority, created_at);

-- ---------------------------------------------------------------- moderation
-- One case per thing that needs a human look: an AI flag, a user report, or an appeal.
CREATE TABLE moderation_cases (
  id           uuid PRIMARY KEY,
  target_kind  text NOT NULL CHECK (target_kind IN ('video', 'comment', 'user')),
  target_id    uuid NOT NULL,
  source       text NOT NULL CHECK (source IN ('ai', 'rules', 'report', 'appeal')),  -- rules = keyword filters
  categories   text[] NOT NULL DEFAULT '{}',
  ai_verdict   jsonb,
  report_count integer NOT NULL DEFAULT 0,
  priority     smallint NOT NULL DEFAULT 2,       -- 0 = child safety or a minor involved
  status       text NOT NULL DEFAULT 'open' CHECK (status IN ('open', 'actioned', 'dismissed')),
  decision     text CHECK (decision IN ('approve', 'reject', 'remove', 'restrict', 'suspend', 'dismiss')),
  decided_by   uuid REFERENCES users(id),
  decision_note text,
  created_at   timestamptz NOT NULL DEFAULT now(),
  decided_at   timestamptz
);
CREATE INDEX moderation_queue_idx ON moderation_cases (status, priority, created_at);
CREATE UNIQUE INDEX moderation_open_target_idx ON moderation_cases (target_kind, target_id) WHERE status = 'open';

-- ---------------------------------------------------------------- verification
-- Status is set by staff only. Documents are stored privately and never shown publicly.
CREATE TABLE verification_requests (
  id           uuid PRIMARY KEY,
  user_id      uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  kind         text NOT NULL CHECK (kind IN ('player', 'scout')),
  status       text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected')),
  organization text,
  evidence     text,                              -- free-text links or explanation from the applicant
  decided_by   uuid REFERENCES users(id),
  decided_at   timestamptz,
  created_at   timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX verification_pending_idx ON verification_requests (user_id, kind) WHERE status = 'pending';

-- ---------------------------------------------------------------- challenges
CREATE TABLE challenges (
  id           uuid PRIMARY KEY,
  slug         text NOT NULL UNIQUE CHECK (slug ~ '^[a-z0-9-]{3,60}$'),
  title        jsonb NOT NULL,
  description  jsonb NOT NULL,
  skill_key    text REFERENCES skills(key),
  hashtag      citext,
  starts_at    timestamptz NOT NULL,
  ends_at      timestamptz NOT NULL CHECK (ends_at > starts_at),
  is_demo      boolean NOT NULL DEFAULT false,
  created_by   uuid REFERENCES users(id),
  created_at   timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE challenge_entries (
  challenge_id uuid NOT NULL REFERENCES challenges(id) ON DELETE CASCADE,
  video_id     uuid NOT NULL REFERENCES videos(id) ON DELETE CASCADE,
  created_at   timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (challenge_id, video_id)
);

-- ---------------------------------------------------------------- scouts
CREATE TABLE shortlists (
  id          uuid PRIMARY KEY,
  owner_id    uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  name        text NOT NULL CHECK (char_length(name) BETWEEN 1 AND 80),
  created_at  timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX shortlists_owner_idx ON shortlists (owner_id);

CREATE TABLE shortlist_players (
  shortlist_id uuid NOT NULL REFERENCES shortlists(id) ON DELETE CASCADE,
  player_id    uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  added_at     timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (shortlist_id, player_id)
);

-- Private to the scout who wrote them. Never shown to the player or other scouts.
CREATE TABLE scout_notes (
  id          uuid PRIMARY KEY,
  scout_id    uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  player_id   uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  body        text NOT NULL CHECK (char_length(body) BETWEEN 1 AND 4000),
  created_at  timestamptz NOT NULL DEFAULT now(),
  updated_at  timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX scout_notes_idx ON scout_notes (scout_id, player_id, created_at DESC);

-- Scouts never get a player's contact details. A request goes to the player, or to the guardian for a minor.
CREATE TABLE contact_requests (
  id           uuid PRIMARY KEY,
  scout_id     uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  player_id    uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  routed_to    uuid NOT NULL REFERENCES users(id),
  message      text NOT NULL CHECK (char_length(message) BETWEEN 1 AND 1000),
  status       text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'accepted', 'declined')),
  created_at   timestamptz NOT NULL DEFAULT now(),
  responded_at timestamptz
);
CREATE UNIQUE INDEX contact_pending_idx ON contact_requests (scout_id, player_id) WHERE status = 'pending';

-- ---------------------------------------------------------------- notifications
CREATE TABLE notifications (
  id          uuid PRIMARY KEY,
  user_id     uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  kind        text NOT NULL,
  payload     jsonb NOT NULL DEFAULT '{}',
  read_at     timestamptz,
  created_at  timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX notifications_user_idx ON notifications (user_id, created_at DESC);

-- ---------------------------------------------------------------- jobs
-- Background work queue, claimed with FOR UPDATE SKIP LOCKED. No extra infrastructure needed.
CREATE TABLE jobs (
  id          bigserial PRIMARY KEY,
  kind        text NOT NULL,
  payload     jsonb NOT NULL,
  status      text NOT NULL DEFAULT 'queued' CHECK (status IN ('queued', 'running', 'done', 'failed')),
  attempts    smallint NOT NULL DEFAULT 0,
  max_attempts smallint NOT NULL DEFAULT 3,
  run_after   timestamptz NOT NULL DEFAULT now(),
  locked_at   timestamptz,
  last_error  text,
  created_at  timestamptz NOT NULL DEFAULT now(),
  finished_at timestamptz
);
CREATE INDEX jobs_ready_idx ON jobs (run_after, id) WHERE status = 'queued';

-- ---------------------------------------------------------------- platform
CREATE TABLE outbox (
  id            bigserial PRIMARY KEY,
  topic         text NOT NULL,
  payload       jsonb NOT NULL,
  created_at    timestamptz NOT NULL DEFAULT now(),
  published_at  timestamptz
);
CREATE INDEX outbox_unpublished_idx ON outbox (id) WHERE published_at IS NULL;

CREATE TABLE idempotency_keys (
  user_id       uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  key           text NOT NULL,
  request_hash  text NOT NULL,
  response      jsonb NOT NULL,
  created_at    timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (user_id, key)
);

-- Append-only, enforced by the trigger below.
CREATE TABLE audit_logs (
  id           bigserial PRIMARY KEY,
  actor_id     uuid,
  action       text NOT NULL,
  target_kind  text,
  target_id    uuid,
  metadata     jsonb NOT NULL DEFAULT '{}',
  created_at   timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX audit_logs_target_idx ON audit_logs (target_kind, target_id, created_at DESC);

CREATE FUNCTION audit_logs_append_only() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  RAISE EXCEPTION 'audit_logs is append-only';
END $$;
CREATE TRIGGER audit_logs_no_update BEFORE UPDATE OR DELETE ON audit_logs
  FOR EACH ROW EXECUTE FUNCTION audit_logs_append_only();
