/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Numeric = ColumnType<string, number | string, number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface AgeRecords {
  age_band: string;
  country_code: string;
  dob_encrypted: Buffer;
  guardian_required: boolean;
  recorded_at: Generated<Timestamp>;
  user_id: string;
}

export interface AiCalls {
  attempt: Generated<number>;
  created_at: Generated<Timestamp>;
  effort: string;
  error: string | null;
  id: string;
  input_tokens: Generated<number>;
  latency_ms: number;
  model: string;
  outcome: string;
  output_tokens: Generated<number>;
  provider: string;
  response_model: string | null;
  task: string;
  user_id: string | null;
  video_id: string | null;
}

export interface AnalyticsDaily {
  day: Timestamp;
  dimension: Generated<string>;
  metric: string;
  updated_at: Generated<Timestamp>;
  value: Int8;
}

export interface AnalyticsEvents {
  anon_id: string | null;
  created_at: Generated<Timestamp>;
  id: Generated<Int8>;
  name: string;
  properties: Generated<Json>;
  source: string;
  user_id: string | null;
}

export interface AuditLogs {
  action: string;
  actor_id: string | null;
  created_at: Generated<Timestamp>;
  id: Generated<Int8>;
  metadata: Generated<Json>;
  target_id: string | null;
  target_kind: string | null;
}

export interface BillingCustomers {
  created_at: Generated<Timestamp>;
  provider: string;
  provider_customer_id: string;
  user_id: string;
}

export interface BillingEvents {
  event_id: string;
  processed_at: Generated<Timestamp>;
  provider: string;
  type: string;
}

export interface Blocks {
  blocked_id: string;
  blocker_id: string;
  created_at: Generated<Timestamp>;
}

export interface ChallengeEntries {
  challenge_id: string;
  created_at: Generated<Timestamp>;
  video_id: string;
}

export interface Challenges {
  created_at: Generated<Timestamp>;
  created_by: string | null;
  description: Json;
  ends_at: Timestamp;
  hashtag: string | null;
  id: string;
  is_demo: Generated<boolean>;
  skill_key: string | null;
  slug: string;
  starts_at: Timestamp;
  title: Json;
}

export interface CheckoutSessions {
  completed_at: Timestamp | null;
  coupon_code: string | null;
  created_at: Generated<Timestamp>;
  payer_user_id: string;
  plan_key: string;
  price_id: string;
  provider: string;
  provider_session_id: string;
  status: Generated<string>;
  trial_days: Generated<number>;
  user_id: string;
}

export interface Comments {
  author_id: string;
  body: string;
  created_at: Generated<Timestamp>;
  id: string;
  moderation: Generated<string>;
  parent_id: string | null;
  video_id: string;
}

export interface Consents {
  created_at: Generated<Timestamp>;
  granted: boolean;
  granted_by: string;
  id: string;
  policy_version: string;
  purpose: string;
  subject_user_id: string;
}

export interface ContactRequests {
  created_at: Generated<Timestamp>;
  id: string;
  message: string;
  organization_id: string | null;
  player_id: string;
  responded_at: Timestamp | null;
  routed_to: string;
  scout_id: string;
  status: Generated<string>;
}

export interface CopyrightClaims {
  accurate: boolean;
  claimant_email: string;
  claimant_name: string;
  claimant_user_id: string | null;
  created_at: Generated<Timestamp>;
  decided_at: Timestamp | null;
  description: string;
  good_faith: boolean;
  id: string;
  status: Generated<string>;
  video_id: string;
}

export interface CopyrightCounterNotices {
  created_at: Generated<Timestamp>;
  decided_at: Timestamp | null;
  explanation: string;
  full_name: string;
  good_faith: boolean;
  id: string;
  status: Generated<string>;
  submitted_by: string;
  video_id: string;
}

export interface CouponRedemptions {
  code: string;
  created_at: Generated<Timestamp>;
  provider_session_id: string;
  user_id: string;
}

export interface Coupons {
  active: Generated<boolean>;
  amount_off_minor: number | null;
  code: string;
  created_at: Generated<Timestamp>;
  currency: string | null;
  description: string | null;
  duration: Generated<string>;
  duration_months: number | null;
  kind: Generated<string>;
  max_redemptions: number | null;
  percent_off: number | null;
  plan_keys: string[] | null;
  provider_promotion_code_id: string | null;
  redeemed_count: Generated<number>;
  referrer_user_id: string | null;
  valid_from: Timestamp | null;
  valid_until: Timestamp | null;
}

export interface CrmEntries {
  contact_request_id: string | null;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  id: string;
  organization_id: string | null;
  owner_user_id: string | null;
  player_id: string;
  stage: Generated<string>;
  tags: Generated<string[]>;
  updated_at: Generated<Timestamp>;
}

export interface CrmNotes {
  author_id: string | null;
  body: string;
  created_at: Generated<Timestamp>;
  entry_id: string;
  id: string;
  updated_at: Generated<Timestamp>;
}

export interface CrmStageHistory {
  changed_by: string | null;
  created_at: Generated<Timestamp>;
  entry_id: string;
  from_stage: string | null;
  id: string;
  to_stage: string;
}

export interface FeatureFlags {
  audience: Generated<Json>;
  client_visible: Generated<boolean>;
  created_at: Generated<Timestamp>;
  description: string;
  enabled: Generated<boolean>;
  key: string;
  rollout_percentage: Generated<number>;
  updated_at: Generated<Timestamp>;
  updated_by: string | null;
}

export interface Follows {
  created_at: Generated<Timestamp>;
  followee_id: string;
  follower_id: string;
}

export interface GuardianInvitations {
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  guardian_email: string;
  id: string;
  minor_user_id: string;
  status: Generated<string>;
  token_hash: Buffer;
}

export interface GuardianRelationships {
  created_at: Generated<Timestamp>;
  guardian_user_id: string;
  minor_user_id: string;
  status: Generated<string>;
}

export interface IdempotencyKeys {
  created_at: Generated<Timestamp>;
  key: string;
  request_hash: string;
  response: Json;
  user_id: string;
}

export interface Jobs {
  attempts: Generated<number>;
  created_at: Generated<Timestamp>;
  finished_at: Timestamp | null;
  id: Generated<Int8>;
  kind: string;
  last_error: string | null;
  locked_at: Timestamp | null;
  max_attempts: Generated<number>;
  payload: Json;
  run_after: Generated<Timestamp>;
  status: Generated<string>;
}

export interface JurisdictionRules {
  country_code: string;
  guardian_consent_age: number;
  legally_reviewed: Generated<boolean>;
  minimum_age: Generated<number>;
  source: string | null;
  updated_at: Generated<Timestamp>;
  updated_by: string | null;
}

export interface Likes {
  created_at: Generated<Timestamp>;
  user_id: string;
  video_id: string;
}

export interface ModerationCases {
  ai_verdict: Json | null;
  categories: Generated<string[]>;
  created_at: Generated<Timestamp>;
  decided_at: Timestamp | null;
  decided_by: string | null;
  decision: string | null;
  decision_note: string | null;
  id: string;
  priority: Generated<number>;
  report_count: Generated<number>;
  source: string;
  status: Generated<string>;
  target_id: string;
  target_kind: string;
}

export interface NotificationPreferences {
  announcements: Generated<boolean>;
  challenge: Generated<boolean>;
  comment: Generated<boolean>;
  follower: Generated<boolean>;
  like: Generated<boolean>;
  save_milestone: Generated<boolean>;
  scout_contact: Generated<boolean>;
  shortlist_activity: Generated<boolean>;
  updated_at: Generated<Timestamp>;
  user_id: string;
  verification: Generated<boolean>;
}

export interface Notifications {
  created_at: Generated<Timestamp>;
  id: string;
  kind: string;
  payload: Generated<Json>;
  read_at: Timestamp | null;
  user_id: string;
}

export interface OrganizationInvitations {
  created_at: Generated<Timestamp>;
  email: string;
  expires_at: Timestamp;
  id: string;
  invited_by: string | null;
  organization_id: string;
  responded_at: Timestamp | null;
  responded_by: string | null;
  role: string;
  status: Generated<string>;
  token_hash: Buffer;
}

export interface OrganizationMembers {
  added_by: string | null;
  created_at: Generated<Timestamp>;
  organization_id: string;
  role: string;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface Organizations {
  country_code: string | null;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  deleted_at: Timestamp | null;
  id: string;
  logo_key: string | null;
  name: string;
  status: Generated<string>;
  type: string;
  updated_at: Generated<Timestamp>;
  verified_at: Timestamp | null;
}

export interface Outbox {
  created_at: Generated<Timestamp>;
  id: Generated<Int8>;
  payload: Json;
  published_at: Timestamp | null;
  topic: string;
}

export interface PlanPrices {
  active: Generated<boolean>;
  amount_minor: number;
  billing_interval: string;
  created_at: Generated<Timestamp>;
  currency: string;
  id: string;
  plan_key: string;
  provider_price_id: string | null;
}

export interface Plans {
  active: Generated<boolean>;
  audience: string;
  checkout_mode: string;
  created_at: Generated<Timestamp>;
  descriptions: Json;
  features: Generated<string[]>;
  key: string;
  limits: Generated<Json>;
  names: Json;
  sort_order: Generated<number>;
  tier: string;
  trial_days: Generated<number>;
  updated_at: Generated<Timestamp>;
}

export interface PlayAnswers {
  answered_at: Generated<Timestamp>;
  ms: number;
  option_id: string;
  points: number;
  round_id: string;
  scenario_id: string;
}

export interface PlayChallenges {
  challenger_id: string;
  completed_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  id: string;
  opponent_id: string;
  scenario_ids: string[];
  status: Generated<string>;
  winner_id: string | null;
}

export interface PlayRounds {
  challenge_id: string | null;
  completed_at: Timestamp | null;
  id: string;
  points: Generated<number>;
  scenario_ids: string[];
  started_at: Generated<Timestamp>;
  total_ms: Generated<number>;
  user_id: string;
  xp: Generated<number>;
}

export interface PlayXp {
  created_at: Generated<Timestamp>;
  day: Generated<Timestamp>;
  id: Generated<Int8>;
  ref: string;
  source: string;
  user_id: string;
  xp: number;
}

export interface PlayerProfiles {
  created_at: Generated<Timestamp>;
  height_cm: number | null;
  preferred_foot: string | null;
  primary_position: string | null;
  secondary_positions: Generated<string[]>;
  user_id: string;
}

export interface PrivacySettings {
  allow_analytics: Generated<boolean>;
  allow_contact_requests: Generated<boolean>;
  allow_scout_discovery: Generated<boolean>;
  comments: Generated<string>;
  direct_messages: Generated<boolean>;
  profile_visibility: Generated<string>;
  region_precision: Generated<string>;
  show_age: Generated<boolean>;
  show_country: Generated<boolean>;
  show_region: Generated<boolean>;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface Profiles {
  avatar_key: string | null;
  bio: string | null;
  created_at: Generated<Timestamp>;
  display_name: string;
  handle: string;
  region_id: string | null;
  updated_at: Generated<Timestamp>;
  user_id: string;
  verified_at: Timestamp | null;
}

export interface QualifiedDiscoveries {
  created_at: Generated<Timestamp>;
  day: Timestamp;
  discoverer_id: string;
  discoverer_kind: string;
  player_id: string;
  source: string;
}

export interface RateLimitHits {
  count: number;
  key: string;
  reset_at: Timestamp;
}

export interface RecommendationPreferences {
  history_reset_at: Timestamp | null;
  personalize: Generated<boolean>;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface RecommendationSignals {
  created_at: Generated<Timestamp>;
  kind: Generated<string>;
  target_id: string;
  target_kind: string;
  user_id: string;
}

export interface Regions {
  code: string;
  country_code: string | null;
  id: string;
  kind: string;
  names: Json;
  parent_id: string | null;
}

export interface Reports {
  created_at: Generated<Timestamp>;
  details: string | null;
  id: string;
  priority: Generated<number>;
  reason: string;
  reporter_id: string;
  status: Generated<string>;
  target_id: string;
  target_kind: string;
}

export interface SavedSearches {
  alerts_enabled: Generated<boolean>;
  alerts_since: Generated<Timestamp>;
  created_at: Generated<Timestamp>;
  created_by: string;
  filters: Generated<Json>;
  id: string;
  name: string;
  organization_id: string | null;
  owner_user_id: string | null;
  updated_at: Generated<Timestamp>;
}

export interface SavedSearchHits {
  created_at: Generated<Timestamp>;
  player_id: string;
  saved_search_id: string;
  video_id: string;
}

export interface Saves {
  created_at: Generated<Timestamp>;
  user_id: string;
  video_id: string;
}

export interface ScoutNotes {
  body: string;
  created_at: Generated<Timestamp>;
  id: string;
  player_id: string;
  scout_id: string;
  updated_at: Generated<Timestamp>;
}

export interface ShortlistPlayers {
  added_at: Generated<Timestamp>;
  player_id: string;
  shortlist_id: string;
}

export interface Shortlists {
  created_at: Generated<Timestamp>;
  id: string;
  name: string;
  owner_id: string;
}

export interface Skills {
  category: string;
  key: string;
  names: Json;
  sort_order: Generated<number>;
}

export interface Subscriptions {
  amount_minor: number | null;
  billing_interval: string | null;
  cancel_at_period_end: Generated<boolean>;
  cancel_reason: string | null;
  cancel_requested_at: Timestamp | null;
  canceled_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  currency: string | null;
  current_period_end: Timestamp | null;
  id: string;
  payer_user_id: string | null;
  plan_key: string;
  provider: string;
  provider_cancel_attempts: Generated<number>;
  provider_cancel_error: string | null;
  provider_canceled_at: Timestamp | null;
  provider_customer_id: string | null;
  provider_event_at: Timestamp;
  provider_subscription_id: string;
  status: string;
  trial_end: Timestamp | null;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface UsageCounters {
  count: Generated<number>;
  metric: string;
  period: string;
  user_id: string;
}

export interface UserRoles {
  granted_at: Generated<Timestamp>;
  granted_by: string | null;
  role: string;
  user_id: string;
}

export interface Users {
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  deletion_requested_at: Timestamp | null;
  email: string | null;
  email_verified: Generated<boolean>;
  id: string;
  idp_subject: string;
  is_demo: Generated<boolean>;
  locale: Generated<string>;
  status: Generated<string>;
}

export interface VerificationRequests {
  created_at: Generated<Timestamp>;
  decided_at: Timestamp | null;
  decided_by: string | null;
  evidence: string | null;
  id: string;
  kind: string;
  organization: string | null;
  organization_id: string | null;
  status: Generated<string>;
  user_id: string;
}

export interface VideoHashtags {
  tag: string;
  video_id: string;
}

export interface Videos {
  ai_model: string | null;
  ai_summary: Json | null;
  context: string | null;
  created_at: Generated<Timestamp>;
  declared_type: string;
  deleted_at: Timestamp | null;
  delivery_purged_at: Timestamp | null;
  description: string | null;
  detected_format: string | null;
  duration_ms: number | null;
  foot: string | null;
  football_present: boolean | null;
  height: number | null;
  id: string;
  max_duration_ms: number | null;
  moderation: string | null;
  original_key: string;
  original_purged_at: Timestamp | null;
  owner_user_id: string;
  playback_key: string | null;
  players_visible: number | null;
  position: string | null;
  published_at: Timestamp | null;
  region_id: string | null;
  rights_confirmed_at: Timestamp | null;
  sha256: Buffer | null;
  size_bytes: Int8;
  skill_key: string | null;
  status: Generated<string>;
  status_reason: string | null;
  thumbnail_key: string | null;
  title: string;
  trim_end_ms: number | null;
  trim_start_ms: number | null;
  visibility: Generated<string>;
  width: number | null;
}

export interface VideoSkills {
  confidence: Numeric | null;
  created_at: Generated<Timestamp>;
  model: string | null;
  skill_key: string;
  source: string;
  status: Generated<string>;
  video_id: string;
}

export interface VideoViews {
  day: Timestamp;
  video_id: string;
  viewer_key: string;
}

export interface DB {
  age_records: AgeRecords;
  ai_calls: AiCalls;
  analytics_daily: AnalyticsDaily;
  analytics_events: AnalyticsEvents;
  audit_logs: AuditLogs;
  billing_customers: BillingCustomers;
  billing_events: BillingEvents;
  blocks: Blocks;
  challenge_entries: ChallengeEntries;
  challenges: Challenges;
  checkout_sessions: CheckoutSessions;
  comments: Comments;
  consents: Consents;
  contact_requests: ContactRequests;
  copyright_claims: CopyrightClaims;
  copyright_counter_notices: CopyrightCounterNotices;
  coupon_redemptions: CouponRedemptions;
  coupons: Coupons;
  crm_entries: CrmEntries;
  crm_notes: CrmNotes;
  crm_stage_history: CrmStageHistory;
  feature_flags: FeatureFlags;
  follows: Follows;
  guardian_invitations: GuardianInvitations;
  guardian_relationships: GuardianRelationships;
  idempotency_keys: IdempotencyKeys;
  jobs: Jobs;
  jurisdiction_rules: JurisdictionRules;
  likes: Likes;
  moderation_cases: ModerationCases;
  notification_preferences: NotificationPreferences;
  notifications: Notifications;
  organization_invitations: OrganizationInvitations;
  organization_members: OrganizationMembers;
  organizations: Organizations;
  outbox: Outbox;
  plan_prices: PlanPrices;
  plans: Plans;
  play_answers: PlayAnswers;
  play_challenges: PlayChallenges;
  play_rounds: PlayRounds;
  play_xp: PlayXp;
  player_profiles: PlayerProfiles;
  privacy_settings: PrivacySettings;
  profiles: Profiles;
  qualified_discoveries: QualifiedDiscoveries;
  rate_limit_hits: RateLimitHits;
  recommendation_preferences: RecommendationPreferences;
  recommendation_signals: RecommendationSignals;
  regions: Regions;
  reports: Reports;
  saved_search_hits: SavedSearchHits;
  saved_searches: SavedSearches;
  saves: Saves;
  scout_notes: ScoutNotes;
  shortlist_players: ShortlistPlayers;
  shortlists: Shortlists;
  skills: Skills;
  subscriptions: Subscriptions;
  usage_counters: UsageCounters;
  user_roles: UserRoles;
  users: Users;
  verification_requests: VerificationRequests;
  video_hashtags: VideoHashtags;
  video_skills: VideoSkills;
  video_views: VideoViews;
  videos: Videos;
}
