/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Numeric = ColumnType<string, number | string, number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface AgeRecords {
  age_band: string;
  country_code: string;
  dob_encrypted: Buffer;
  guardian_required: boolean;
  recorded_at: Generated<Timestamp>;
  user_id: string;
}

export interface AuditLogs {
  action: string;
  actor_id: string | null;
  created_at: Generated<Timestamp>;
  id: Generated<Int8>;
  metadata: Generated<Json>;
  target_id: string | null;
  target_kind: string | null;
}

export interface Blocks {
  blocked_id: string;
  blocker_id: string;
  created_at: Generated<Timestamp>;
}

export interface ChallengeEntries {
  challenge_id: string;
  created_at: Generated<Timestamp>;
  video_id: string;
}

export interface Challenges {
  created_at: Generated<Timestamp>;
  created_by: string | null;
  description: Json;
  ends_at: Timestamp;
  hashtag: string | null;
  id: string;
  is_demo: Generated<boolean>;
  skill_key: string | null;
  slug: string;
  starts_at: Timestamp;
  title: Json;
}

export interface Comments {
  author_id: string;
  body: string;
  created_at: Generated<Timestamp>;
  id: string;
  moderation: Generated<string>;
  parent_id: string | null;
  video_id: string;
}

export interface Consents {
  created_at: Generated<Timestamp>;
  granted: boolean;
  granted_by: string;
  id: string;
  policy_version: string;
  purpose: string;
  subject_user_id: string;
}

export interface ContactRequests {
  created_at: Generated<Timestamp>;
  id: string;
  message: string;
  player_id: string;
  responded_at: Timestamp | null;
  routed_to: string;
  scout_id: string;
  status: Generated<string>;
}

export interface Follows {
  created_at: Generated<Timestamp>;
  followee_id: string;
  follower_id: string;
}

export interface GuardianInvitations {
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  guardian_email: string;
  id: string;
  minor_user_id: string;
  status: Generated<string>;
  token_hash: Buffer;
}

export interface GuardianRelationships {
  created_at: Generated<Timestamp>;
  guardian_user_id: string;
  minor_user_id: string;
  status: Generated<string>;
}

export interface IdempotencyKeys {
  created_at: Generated<Timestamp>;
  key: string;
  request_hash: string;
  response: Json;
  user_id: string;
}

export interface Jobs {
  attempts: Generated<number>;
  created_at: Generated<Timestamp>;
  finished_at: Timestamp | null;
  id: Generated<Int8>;
  kind: string;
  last_error: string | null;
  locked_at: Timestamp | null;
  max_attempts: Generated<number>;
  payload: Json;
  run_after: Generated<Timestamp>;
  status: Generated<string>;
}

export interface JurisdictionRules {
  country_code: string;
  guardian_consent_age: number;
  legally_reviewed: Generated<boolean>;
  minimum_age: Generated<number>;
  source: string | null;
  updated_at: Generated<Timestamp>;
  updated_by: string | null;
}

export interface Likes {
  created_at: Generated<Timestamp>;
  user_id: string;
  video_id: string;
}

export interface ModerationCases {
  ai_verdict: Json | null;
  categories: Generated<string[]>;
  created_at: Generated<Timestamp>;
  decided_at: Timestamp | null;
  decided_by: string | null;
  decision: string | null;
  decision_note: string | null;
  id: string;
  priority: Generated<number>;
  report_count: Generated<number>;
  source: string;
  status: Generated<string>;
  target_id: string;
  target_kind: string;
}

export interface Notifications {
  created_at: Generated<Timestamp>;
  id: string;
  kind: string;
  payload: Generated<Json>;
  read_at: Timestamp | null;
  user_id: string;
}

export interface Outbox {
  created_at: Generated<Timestamp>;
  id: Generated<Int8>;
  payload: Json;
  published_at: Timestamp | null;
  topic: string;
}

export interface PlayerProfiles {
  created_at: Generated<Timestamp>;
  height_cm: number | null;
  preferred_foot: string | null;
  primary_position: string | null;
  secondary_positions: Generated<string[]>;
  user_id: string;
}

export interface PrivacySettings {
  comments: Generated<string>;
  direct_messages: Generated<boolean>;
  profile_visibility: Generated<string>;
  region_precision: Generated<string>;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface Profiles {
  avatar_key: string | null;
  bio: string | null;
  created_at: Generated<Timestamp>;
  display_name: string;
  handle: string;
  region_id: string | null;
  updated_at: Generated<Timestamp>;
  user_id: string;
  verified_at: Timestamp | null;
}

export interface Regions {
  code: string;
  country_code: string | null;
  id: string;
  kind: string;
  names: Json;
  parent_id: string | null;
}

export interface Reports {
  created_at: Generated<Timestamp>;
  details: string | null;
  id: string;
  priority: Generated<number>;
  reason: string;
  reporter_id: string;
  status: Generated<string>;
  target_id: string;
  target_kind: string;
}

export interface Saves {
  created_at: Generated<Timestamp>;
  user_id: string;
  video_id: string;
}

export interface ScoutNotes {
  body: string;
  created_at: Generated<Timestamp>;
  id: string;
  player_id: string;
  scout_id: string;
  updated_at: Generated<Timestamp>;
}

export interface ShortlistPlayers {
  added_at: Generated<Timestamp>;
  player_id: string;
  shortlist_id: string;
}

export interface Shortlists {
  created_at: Generated<Timestamp>;
  id: string;
  name: string;
  owner_id: string;
}

export interface Skills {
  category: string;
  key: string;
  names: Json;
  sort_order: Generated<number>;
}

export interface UserRoles {
  granted_at: Generated<Timestamp>;
  granted_by: string | null;
  role: string;
  user_id: string;
}

export interface Users {
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  email: string | null;
  email_verified: Generated<boolean>;
  id: string;
  idp_subject: string;
  is_demo: Generated<boolean>;
  locale: Generated<string>;
  status: Generated<string>;
}

export interface VerificationRequests {
  created_at: Generated<Timestamp>;
  decided_at: Timestamp | null;
  decided_by: string | null;
  evidence: string | null;
  id: string;
  kind: string;
  organization: string | null;
  status: Generated<string>;
  user_id: string;
}

export interface VideoHashtags {
  tag: string;
  video_id: string;
}

export interface Videos {
  ai_summary: Json | null;
  context: string | null;
  created_at: Generated<Timestamp>;
  declared_type: string;
  deleted_at: Timestamp | null;
  description: string | null;
  detected_format: string | null;
  duration_ms: number | null;
  foot: string | null;
  football_present: boolean | null;
  height: number | null;
  id: string;
  moderation: string | null;
  original_key: string;
  owner_user_id: string;
  playback_key: string | null;
  players_visible: number | null;
  position: string | null;
  published_at: Timestamp | null;
  region_id: string | null;
  sha256: Buffer | null;
  size_bytes: Int8;
  skill_key: string | null;
  status: Generated<string>;
  status_reason: string | null;
  thumbnail_key: string | null;
  title: string;
  trim_end_ms: number | null;
  trim_start_ms: number | null;
  visibility: Generated<string>;
  width: number | null;
}

export interface VideoSkills {
  confidence: Numeric | null;
  created_at: Generated<Timestamp>;
  skill_key: string;
  source: string;
  status: Generated<string>;
  video_id: string;
}

export interface VideoViews {
  day: Timestamp;
  video_id: string;
  viewer_key: string;
}

export interface DB {
  age_records: AgeRecords;
  audit_logs: AuditLogs;
  blocks: Blocks;
  challenge_entries: ChallengeEntries;
  challenges: Challenges;
  comments: Comments;
  consents: Consents;
  contact_requests: ContactRequests;
  follows: Follows;
  guardian_invitations: GuardianInvitations;
  guardian_relationships: GuardianRelationships;
  idempotency_keys: IdempotencyKeys;
  jobs: Jobs;
  jurisdiction_rules: JurisdictionRules;
  likes: Likes;
  moderation_cases: ModerationCases;
  notifications: Notifications;
  outbox: Outbox;
  player_profiles: PlayerProfiles;
  privacy_settings: PrivacySettings;
  profiles: Profiles;
  regions: Regions;
  reports: Reports;
  saves: Saves;
  scout_notes: ScoutNotes;
  shortlist_players: ShortlistPlayers;
  shortlists: Shortlists;
  skills: Skills;
  user_roles: UserRoles;
  users: Users;
  verification_requests: VerificationRequests;
  video_hashtags: VideoHashtags;
  video_skills: VideoSkills;
  video_views: VideoViews;
  videos: Videos;
}
