/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type ArrayType<T> = ArrayTypeImpl<T> extends (infer U)[]
  ? U[]
  : ArrayTypeImpl<T>;

export type ArrayTypeImpl<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S[], I[], U[]>
  : T[];

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Numeric = ColumnType<number, number | string, number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface AgentRuns {
  agent: string;
  analysis_run_id: string;
  cache_key: string | null;
  confidence: Numeric | null;
  cost_usd_micros: Int8 | null;
  created_at: Generated<Timestamp>;
  errors: Generated<Json>;
  id: string;
  latency_ms: number | null;
  limitations: Generated<Json>;
  status: string;
  version: string;
}

export interface AgeRecords {
  age_band: string;
  country_code: string;
  dob_encrypted: Buffer;
  guardian_required: boolean;
  recorded_at: Generated<Timestamp>;
  user_id: string;
}

export interface AnalysisRuns {
  cost_usd_micros: Int8 | null;
  created_at: Generated<Timestamp>;
  finished_at: Timestamp | null;
  id: string;
  limitations: Generated<Json>;
  pipeline_version: string;
  quality_score: Numeric | null;
  readiness: Numeric | null;
  requested_by: string;
  status: Generated<string>;
  target_selection_id: string;
  tier: string;
  video_id: string;
}

export interface AuditLogs {
  action: string;
  actor_id: string | null;
  created_at: Generated<Timestamp>;
  id: Generated<Int8>;
  metadata: Generated<Json>;
  target_id: string | null;
  target_kind: string | null;
}

export interface Blocks {
  blocked_id: string;
  blocker_id: string;
  created_at: Generated<Timestamp>;
}

export interface Comments {
  author_id: string;
  body: string;
  created_at: Generated<Timestamp>;
  id: string;
  moderation: Generated<string>;
  parent_id: string | null;
  video_id: string;
}

export interface Consents {
  created_at: Generated<Timestamp>;
  granted: boolean;
  granted_by: string;
  id: string;
  policy_version: string;
  purpose: string;
  subject_user_id: string;
}

export interface Follows {
  created_at: Generated<Timestamp>;
  followee_id: string;
  follower_id: string;
}

export interface GuardianInvitations {
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  guardian_email: string;
  id: string;
  minor_user_id: string;
  status: Generated<string>;
  token_hash: Buffer;
}

export interface GuardianRelationships {
  created_at: Generated<Timestamp>;
  guardian_user_id: string;
  minor_user_id: string;
  status: Generated<string>;
}

export interface IdempotencyKeys {
  created_at: Generated<Timestamp>;
  key: string;
  request_hash: string;
  response: Json;
  user_id: string;
}

export interface Likes {
  created_at: Generated<Timestamp>;
  user_id: string;
  video_id: string;
}

export interface Observations {
  agent_run_id: string;
  analysis_run_id: string;
  confidence: Numeric;
  context: Generated<Json>;
  event_type: string;
  excluded_reason: string | null;
  id: string;
  outcome: string;
  skill: string;
  t_end_ms: number;
  t_start_ms: number;
}

export interface Outbox {
  created_at: Generated<Timestamp>;
  id: Generated<Int8>;
  payload: Json;
  published_at: Timestamp | null;
  topic: string;
}

export interface PlayerDnaVersions {
  created_at: Generated<Timestamp>;
  dna: Json;
  id: string;
  method_version: string;
  player_user_id: string;
  version: number;
}

export interface PlayerProfiles {
  created_at: Generated<Timestamp>;
  height_cm: number | null;
  preferred_foot: string | null;
  primary_position: string | null;
  secondary_positions: Generated<string[]>;
  user_id: string;
}

export interface PopularityScores {
  computed_at: Generated<Timestamp>;
  score: Numeric;
  user_id: string;
}

export interface PrivacySettings {
  comments: Generated<string>;
  direct_messages: Generated<boolean>;
  profile_visibility: Generated<string>;
  region_precision: Generated<string>;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface Profiles {
  avatar_key: string | null;
  bio: string | null;
  created_at: Generated<Timestamp>;
  display_name: string;
  handle: string;
  region_id: string | null;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface Regions {
  code: string;
  country_code: string | null;
  id: string;
  kind: string;
  names: Json;
  parent_id: string | null;
}

export interface Reports {
  created_at: Generated<Timestamp>;
  details: string | null;
  id: string;
  priority: Generated<number>;
  reason: string;
  reporter_id: string;
  status: Generated<string>;
  target_id: string;
  target_kind: string;
}

export interface SkillScoreEvidence {
  observation_id: string;
  skill_score_id: string;
  weight: Numeric;
}

export interface SkillScores {
  computed_at: Generated<Timestamp>;
  confidence: Numeric;
  evidence_count: number;
  evidence_quality: string;
  explanation: Json;
  id: string;
  method_version: string;
  player_user_id: string;
  score: Numeric | null;
  skill: string;
  status: string;
  superseded_by: string | null;
}

export interface TargetSelections {
  box: Json;
  claimed_player_id: string | null;
  confirmed: Generated<boolean>;
  created_at: Generated<Timestamp>;
  frame_ms: number;
  id: string;
  selected_by: string;
  video_id: string;
}

export interface TrustScores {
  computed_at: Generated<Timestamp>;
  score: Numeric;
  user_id: string;
}

export interface UserRoles {
  granted_at: Generated<Timestamp>;
  granted_by: string | null;
  role: string;
  user_id: string;
}

export interface Users {
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  email: string | null;
  email_verified: Generated<boolean>;
  id: string;
  idp_subject: string;
  locale: Generated<string>;
  status: Generated<string>;
}

export interface VideoHashes {
  phash: ArrayType<Int8> | null;
  sha256: Buffer;
  video_id: string;
}

export interface Videos {
  caption: string | null;
  content_type: string;
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  duration_ms: number | null;
  fps: Numeric | null;
  height: number | null;
  hls_key: string | null;
  id: string;
  original_key: string;
  owner_user_id: string;
  ready_at: Timestamp | null;
  region_id: string | null;
  size_bytes: Int8;
  status: Generated<string>;
  subject: string;
  thumbnail_key: string | null;
  video_type: string;
  visibility: Generated<string>;
  width: number | null;
}

export interface DB {
  age_records: AgeRecords;
  agent_runs: AgentRuns;
  analysis_runs: AnalysisRuns;
  audit_logs: AuditLogs;
  blocks: Blocks;
  comments: Comments;
  consents: Consents;
  follows: Follows;
  guardian_invitations: GuardianInvitations;
  guardian_relationships: GuardianRelationships;
  idempotency_keys: IdempotencyKeys;
  likes: Likes;
  observations: Observations;
  outbox: Outbox;
  player_dna_versions: PlayerDnaVersions;
  player_profiles: PlayerProfiles;
  popularity_scores: PopularityScores;
  privacy_settings: PrivacySettings;
  profiles: Profiles;
  regions: Regions;
  reports: Reports;
  skill_score_evidence: SkillScoreEvidence;
  skill_scores: SkillScores;
  target_selections: TargetSelections;
  trust_scores: TrustScores;
  user_roles: UserRoles;
  users: Users;
  video_hashes: VideoHashes;
  videos: Videos;
}
