/** API types, inferred from the shared Zod contracts. Nothing here is declared twice. */
import type { z } from 'zod';
import type * as C from '@fp/contracts';

export type Problem = z.infer<typeof C.Problem>;
export type Locale = z.infer<typeof C.Locale>;
export type Position = z.infer<typeof C.Position>;
export type Foot = z.infer<typeof C.Foot>;
export type SkillKey = z.infer<typeof C.SkillKey>;
export type Bilingual = z.infer<typeof C.Bilingual>;
export type AgeBand = z.infer<typeof C.AgeBand>;
export type Capability = z.infer<typeof C.Capability>;
export type CapabilityStatus = z.infer<typeof C.CapabilityStatus>;

export type RegisterRequest = z.input<typeof C.RegisterRequest>;
export type RegisterResponse = z.infer<typeof C.RegisterResponse>;
export type GuardianInviteRequest = z.input<typeof C.GuardianInviteRequest>;
export type GuardianInviteResponse = z.infer<typeof C.GuardianInviteResponse>;
export type GuardianAcceptRequest = z.input<typeof C.GuardianAcceptRequest>;
export type ConsentPurpose = z.infer<typeof C.ConsentPurpose>;
export type ConsentRequest = z.input<typeof C.ConsentRequest>;
export type ConsentState = z.infer<typeof C.ConsentState>;

export type ProfileView = z.infer<typeof C.ProfileView>;
export type UpdateProfileRequest = z.input<typeof C.UpdateProfileRequest>;
export type MeView = z.infer<typeof C.MeView>;
export type SkillView = z.infer<typeof C.SkillView>;
export type SkillList = z.infer<typeof C.SkillList>;

export type VideoContentType = z.infer<typeof C.VideoContentType>;
export type VideoStatus = z.infer<typeof C.VideoStatus>;
export type SafetyStatus = z.infer<typeof C.SafetyStatus>;
export type VideoContext = z.infer<typeof C.VideoContext>;
export type Visibility = z.infer<typeof C.Visibility>;
export type CreateUploadRequest = z.input<typeof C.CreateUploadRequest>;
export type CreateUploadResponse = z.infer<typeof C.CreateUploadResponse>;
export type UpdateVideoRequest = z.input<typeof C.UpdateVideoRequest>;
export type VideoTag = z.infer<typeof C.VideoTag>;
export type TagCorrectionRequest = z.input<typeof C.TagCorrectionRequest>;
export type VideoView = z.infer<typeof C.VideoView>;
export type VideoPage = z.infer<typeof C.VideoPage>;

export type FeedTab = z.infer<typeof C.FeedTab>;
export type FeedPage = z.infer<typeof C.FeedPage>;
export type CreateCommentRequest = z.input<typeof C.CreateCommentRequest>;
export type CommentView = z.infer<typeof C.CommentView>;
export type CommentPage = z.infer<typeof C.CommentPage>;
export type ReportReason = z.infer<typeof C.ReportReason>;
export type ReportRequest = z.input<typeof C.ReportRequest>;

export type PlayerCard = z.infer<typeof C.PlayerCard>;
export type SearchQuery = z.input<typeof C.SearchQuery>;
export type SearchResult = z.infer<typeof C.SearchResult>;
export type RadarCategory = z.infer<typeof C.RadarCategory>;
export type FeedWhy = z.infer<typeof C.FeedWhy>;
export type NlScoutSearchRequest = z.input<typeof C.NlScoutSearchRequest>;
export type NlScoutSearchResponse = z.infer<typeof C.NlScoutSearchResponse>;
export type RecommendationSettingsView = z.infer<typeof C.RecommendationSettingsView>;
export type UpdateRecommendationSettingsRequest = z.input<typeof C.UpdateRecommendationSettingsRequest>;
export type AiUsageView = z.infer<typeof C.AiUsageView>;
export type RadarQuery = z.input<typeof C.RadarQuery>;
export type RadarPage = z.infer<typeof C.RadarPage>;
export type ChallengeView = z.infer<typeof C.ChallengeView>;
export type ChallengeList = z.infer<typeof C.ChallengeList>;
export type CreateChallengeRequest = z.input<typeof C.CreateChallengeRequest>;
export type EnterChallengeRequest = z.input<typeof C.EnterChallengeRequest>;
export type DiscoverView = z.infer<typeof C.DiscoverView>;

export type ScoutSearchQuery = z.input<typeof C.ScoutSearchQuery>;
export type PlayerPage = z.infer<typeof C.PlayerPage>;
export type ShortlistView = z.infer<typeof C.ShortlistView>;
export type ShortlistList = z.infer<typeof C.ShortlistList>;
export type ShortlistDetail = z.infer<typeof C.ShortlistDetail>;
export type CreateShortlistRequest = z.input<typeof C.CreateShortlistRequest>;
export type ScoutNoteView = z.infer<typeof C.ScoutNoteView>;
export type ScoutNoteList = z.infer<typeof C.ScoutNoteList>;
export type CreateScoutNoteRequest = z.input<typeof C.CreateScoutNoteRequest>;
export type ContactRequestCreate = z.input<typeof C.ContactRequestCreate>;
export type ContactRequestView = z.infer<typeof C.ContactRequestView>;
export type ContactRequestList = z.infer<typeof C.ContactRequestList>;
export type ContactResponseRequest = z.input<typeof C.ContactResponseRequest>;
export type VerificationRequestCreate = z.input<typeof C.VerificationRequestCreate>;
export type VerificationRequestView = z.infer<typeof C.VerificationRequestView>;
export type VerificationRequestList = z.infer<typeof C.VerificationRequestList>;

export type NotificationView = z.infer<typeof C.NotificationView>;
export type NotificationPage = z.infer<typeof C.NotificationPage>;
export type MarkReadRequest = z.input<typeof C.MarkReadRequest>;

export type ModerationCaseView = z.infer<typeof C.ModerationCaseView>;
export type ModerationCaseList = z.infer<typeof C.ModerationCaseList>;
export type ModerationDecisionRequest = z.input<typeof C.ModerationDecisionRequest>;
export type VerificationDecisionRequest = z.input<typeof C.VerificationDecisionRequest>;
export type AuditLogView = z.infer<typeof C.AuditLogView>;
export type AuditLogPage = z.infer<typeof C.AuditLogPage>;
export type AdminStats = z.infer<typeof C.AdminStats>;

export type ProfileVisibility = z.infer<typeof C.ProfileVisibility>;
export type PrivacySettingsView = z.infer<typeof C.PrivacySettingsView>;
export type UpdatePrivacyRequest = z.input<typeof C.UpdatePrivacyRequest>;
export type NotificationPreferencesView = z.infer<typeof C.NotificationPreferencesView>;
export type NotificationPreferenceKey = Exclude<keyof NotificationPreferencesView, 'security'>;
export type UpdateNotificationPreferencesRequest = z.input<typeof C.UpdateNotificationPreferencesRequest>;
export type AccountExport = z.infer<typeof C.AccountExport>;
export type DeleteAccountRequest = z.input<typeof C.DeleteAccountRequest>;
export type DeleteAccountResponse = z.infer<typeof C.DeleteAccountResponse>;
export type CopyrightTakedownRequest = z.input<typeof C.CopyrightTakedownRequest>;
export type CopyrightTakedownResponse = z.infer<typeof C.CopyrightTakedownResponse>;
export type CounterNoticeRequest = z.input<typeof C.CounterNoticeRequest>;

export type OrgType = z.infer<typeof C.OrgType>;
export type OrgRole = z.infer<typeof C.OrgRole>;
export type InvitableOrgRole = z.infer<typeof C.InvitableOrgRole>;
export type CreateOrganizationRequest = z.input<typeof C.CreateOrganizationRequest>;
export type UpdateOrganizationRequest = z.input<typeof C.UpdateOrganizationRequest>;
export type OrganizationPublicView = z.infer<typeof C.OrganizationPublicView>;
export type OrganizationMemberView = z.infer<typeof C.OrganizationMemberView>;
export type OrganizationInvitationView = z.infer<typeof C.OrganizationInvitationView>;
export type OrganizationDashboard = z.infer<typeof C.OrganizationDashboard>;
export type MyOrganizations = z.infer<typeof C.MyOrganizations>;
export type CreateOrgInvitationRequest = z.input<typeof C.CreateOrgInvitationRequest>;
export type CreateOrgInvitationResponse = z.infer<typeof C.CreateOrgInvitationResponse>;
export type OrgInvitationTokenRequest = z.input<typeof C.OrgInvitationTokenRequest>;
export type AcceptOrgInvitationResponse = z.infer<typeof C.AcceptOrgInvitationResponse>;
export type UpdateOrgMemberRequest = z.input<typeof C.UpdateOrgMemberRequest>;
export type VerificationKind = z.infer<typeof C.VerificationKind>;

export type CrmStage = z.infer<typeof C.CrmStage>;
export type CrmEntryView = z.infer<typeof C.CrmEntryView>;
export type CrmEntryDetail = z.infer<typeof C.CrmEntryDetail>;
export type CrmNoteView = z.infer<typeof C.CrmNoteView>;
export type PipelineQuery = z.input<typeof C.PipelineQuery>;
export type PipelineView = z.infer<typeof C.PipelineView>;
export type AddToPipelineRequest = z.input<typeof C.AddToPipelineRequest>;
export type CrmStageChangeRequest = z.input<typeof C.CrmStageChangeRequest>;
export type CreateCrmNoteRequest = z.input<typeof C.CreateCrmNoteRequest>;
export type SavedSearchView = z.infer<typeof C.SavedSearchView>;
export type SavedSearchList = z.infer<typeof C.SavedSearchList>;
export type CreateSavedSearchRequest = z.input<typeof C.CreateSavedSearchRequest>;
export type UpdateSavedSearchRequest = z.input<typeof C.UpdateSavedSearchRequest>;
export type BillingInterval = z.infer<typeof C.BillingInterval>;
export type PlanAudience = z.infer<typeof C.PlanAudience>;
export type PlanLimits = z.infer<typeof C.PlanLimits>;
export type PlanPrice = z.infer<typeof C.PlanPrice>;
export type PlanView = z.infer<typeof C.PlanView>;
export type PlanList = z.infer<typeof C.PlanList>;
export type SubscriptionView = z.infer<typeof C.SubscriptionView>;
export type EntitlementsView = z.infer<typeof C.EntitlementsView>;
export type CheckoutRequest = z.input<typeof C.CheckoutRequest>;
export type CheckoutResponse = z.infer<typeof C.CheckoutResponse>;
export type PortalResponse = z.infer<typeof C.PortalResponse>;
export type CouponValidateRequest = z.input<typeof C.CouponValidateRequest>;
export type CouponView = z.infer<typeof C.CouponView>;

// analytics, flags, metrics, SEO (Phase E1)
export type ClientEventName = C.ClientEventName;
export type TrackEventsRequest = z.input<typeof C.TrackEventsRequest>;
export type TrackEventsResponse = z.infer<typeof C.TrackEventsResponse>;
export type AdminMetrics = z.infer<typeof C.AdminMetrics>;
export type MetricPoint = z.infer<typeof C.MetricPoint>;
export type FunnelView = z.infer<typeof C.FunnelView>;
export type EvaluatedFlags = z.infer<typeof C.EvaluatedFlags>;
export type FeatureFlagView = z.infer<typeof C.FeatureFlagView>;
export type SitemapView = z.infer<typeof C.SitemapView>;
export type SeoProfileView = z.infer<typeof C.SeoProfileView>;
export type GuardianCaseDetails = z.infer<typeof C.GuardianCaseDetails>;
export type GuardianScanView = z.infer<typeof C.GuardianScanView>;
export type GuardianMetricsView = z.infer<typeof C.GuardianMetricsView>;
export type CasePreview = z.infer<typeof C.CasePreview>;
export type AppealRequest = z.input<typeof C.AppealRequest>;
export type AppealView = z.infer<typeof C.AppealView>;
export type RescanQueued = z.infer<typeof C.RescanQueued>;
